version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: ~/leakcheck
    
    steps:
      - checkout
      - run: go get -v -d ./...
      - run: go build .
      # - run: go test -exec ./leakcheck -v ./...
      - run: go test -exec ./leakcheck -v .