version: 2
jobs:
  build:
    docker:
      - image: circleci/golang:1.11

    working_directory: $HOME/leakcheck
    steps:
      - checkout

      - run: go get -v -t -d ./...
      - run: go build .
      - run: go test -exec ./leakcheck -v ./...