package syscalls

import "syscall"

var _ = syscall.Exit

var Name = map[uint64]string{
	syscall.SYS_SYSR1:       "sysr1",
	syscall.SYS_BIND:        "bind",
	syscall.SYS_CHDIR:       "chdir",
	syscall.SYS_CLOSE:       "close",
	syscall.SYS_DUP:         "dup",
	syscall.SYS_ALARM:       "alarm",
	syscall.SYS_EXEC:        "exec",
	syscall.SYS_EXITS:       "exits",
	syscall.SYS_FAUTH:       "fauth",
	syscall.SYS_SEGBRK:      "segbrk",
	syscall.SYS_OPEN:        "open",
	syscall.SYS_OSEEK:       "oseek",
	syscall.SYS_SLEEP:       "sleep",
	syscall.SYS_RFORK:       "rfork",
	syscall.SYS_PIPE:        "pipe",
	syscall.SYS_CREATE:      "create",
	syscall.SYS_FD2PATH:     "fd2path",
	syscall.SYS_BRK_:        "brk_",
	syscall.SYS_REMOVE:      "remove",
	syscall.SYS_NOTIFY:      "notify",
	syscall.SYS_NOTED:       "noted",
	syscall.SYS_SEGATTACH:   "segattach",
	syscall.SYS_SEGDETACH:   "segdetach",
	syscall.SYS_SEGFREE:     "segfree",
	syscall.SYS_SEGFLUSH:    "segflush",
	syscall.SYS_RENDEZVOUS:  "rendezvous",
	syscall.SYS_UNMOUNT:     "unmount",
	syscall.SYS_SEMACQUIRE:  "semacquire",
	syscall.SYS_SEMRELEASE:  "semrelease",
	syscall.SYS_SEEK:        "seek",
	syscall.SYS_FVERSION:    "fversion",
	syscall.SYS_ERRSTR:      "errstr",
	syscall.SYS_STAT:        "stat",
	syscall.SYS_FSTAT:       "fstat",
	syscall.SYS_WSTAT:       "wstat",
	syscall.SYS_FWSTAT:      "fwstat",
	syscall.SYS_MOUNT:       "mount",
	syscall.SYS_AWAIT:       "await",
	syscall.SYS_PREAD:       "pread",
	syscall.SYS_PWRITE:      "pwrite",
	syscall.SYS_TSEMACQUIRE: "tsemacquire",
	syscall.SYS_NSEC:        "nsec",
}
